language: node_js
node_js:
  - "6.0"
env:
  - APP_VERSION=default
before_install:
  - echo "before_install"
install:
  - npm install --global firebase-tools
before_script:
  - echo "before_script"
script:
  - ng build
after_success:
  - firebase deploy --project "hamed-portfolio" --token "$FIREBASE_TOKEN" --only "hosting" --debug